# Generated by Django 6.0 on 2025-12-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
